#!/bin/bash

GH_URL='https://raw.githubusercontent.com/jeremy-wolfe/frigate-ntfy/refs/heads/main'

curl -O "$GH_URL/docker-compose.yml"
curl -o config.yml "$GH_URL/config.example.yml"
docker compose pull
